# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 74f0d3d7f629959a46ce492452f6b03ed372d7033866711f2643cda3cace852379863cf510724e0d4497a1f07aa7299550825460b9277342da947d7c4fb319f1

test:
  secret_key_base: f2022647595ca818e6010f426347848e37e0129a9492c64d33aaf43b9cd8303dd8df2f5b64aaa4088359a16eac6302b0f7496660c590121e8748d02c7871ba2f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
